spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: be11fe86308a93005780
            client-secret: 5e274aac5e14a47a5724d63c9bdab107c4c349a9
          qq:
            client-id: asd
            client-secret: xx
            provider: qq
            client-name: QQ登录
            authorization-grant-type: authorization_code
            clientAuthenticationMethod: post
            scope: get_user_info,list_album,upload_pic,do_like
            redirect-uri: "{baseUrl}/register/social/qq"
          weibo:
            client-id: 1832512189
            client-secret: 17d6af788fb357169f954ba5952bdefd
            provider: weibo
            client-name: 微博登录
            authorization-grant-type: authorization_code
            clientAuthenticationMethod: post
            redirect-uri: "http://77ewfc.natappfree.cc/return/"

        provider:
          qq:
            authorization-uri: https://graph.qq.com/oauth2.0/authorize
            token-uri: https://graph.qq.com/oauth2.0/token
            user-info-uri: https://graph.qq.com/oauth2.0/me
            user-name-attribute: "nickname"
          weibo:
            authorization-uri: https://api.weibo.com/oauth2/authorize
            token-uri: https://api.weibo.com/oauth2/access_token
            user-info-uri: https://api.weibo.com/oauth2/get_token_info
            user-name-attribute: "name"